baseURL = "https://alessionardin.eu/"
languageCode = "en-US"
title = "Alessio Nardin"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpeg"
  author = "Alessio Nardin"
  description = "Portfolio website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "AlessioNar"
  Email         = "alessio.nardin@gmail.com"
  LinkedIn      = "username"
  Medium        = "username"

## Main Menu

[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 100
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
