baseURL = "https://alessionardin.eu/"
languageCode = "en-US"
title = "Alessio Nardin"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "white-professional"

# Meta tags
[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpeg"
  author = "Alessio Nardin"
  description = "Alessio Nardin personal website. Curriculum, projects, research"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/custom.css"]
  custom_js  = ["js/projects.js"]

[params.social]
  Github        = "AlessioNar"
  Email         = "alessio.nardin@gmail.com"
  LinkedIn      = "alessio-nardin-236a2515a"
  Medium        = "alessio.nardin"

## Main Menu

[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 100
  url = "/projects/"
[[menu.main]]
  name = "CV"
  identifier = ""
  weight = 300
  url = "/cv/curriculum-en"
